-- CREATE TABLE IF NOT EXISTS Station_Descriptions
-- (
--     id SERIAL PRIMARY KEY,
--     line_id INTEGER REFERENCES Lines (id),
--     station_id INTEGER REFERENCES Stations (id),
--     entry_id INTEGER REFERENCES Entries (id),
--     input_doors_count INTEGER,
--     input_doors_bandwidth NUMERIC(10, 2),
--     input_doors_total_bandwidth NUMERIC(10, 2),
--     input_doors_note NUMERIC(10, 2),
--     input_turnstile_count INTEGER,
--     input_turnstile_bandwidth NUMERIC(10, 2),
--     input_turnstile_total_bandwidth NUMERIC(10, 2),
--     input_turnstile_note NUMERIC(10, 2),
--     input_stairs_width NUMERIC(10, 2),
--     input_stairs_bandwidth NUMERIC(10, 2),
--     input_stairs_total_bandwidth NUMERIC(10, 2),
--     input_stairs_note TEXT,
--     input_escalator_count INTEGER,
--     input_escalator_bandwidth NUMERIC(10, 2),
--     input_escalator_total_bandwidth NUMERIC(10, 2),
--     input_escalator_note TEXT,
--     output_doors_count INTEGER,
--     output_doors_bandwidth NUMERIC(10, 2),
--     output_doors_total_bandwidth NUMERIC(10, 2),
--     output_doors_note TEXT,
--     output_turnstile_count INTEGER,
--     output_turnstile_bandwidth NUMERIC(10, 2),
--     output_turnstile_total_bandwidth NUMERIC(10, 2),
--     output_turnstile_note TEXT,
--     output_stairs_width NUMERIC(10, 2),
--     output_stairs_bandwidth NUMERIC(10, 2),
--     output_stairs_total_bandwidth NUMERIC(10, 2),
--     output_stairs_note TEXT,
--     output_escalator_count INTEGER,
--     output_escalator_bandwidth NUMERIC(10, 2),
--     output_escalator_total_bandwidth NUMERIC(10, 2),
--     note TEXT,
--     stop_id INTEGER
-- );

-- CREATE TABLE IF NOT EXISTS Passengers_Flow 
-- (
--     id SERIAL PRIMARY KEY,
--     "date" DATE,
--     "hour" INTEGER,
--     line_id INTEGER REFERENCES Lines (id),
--     station_id INTEGER REFERENCES Stations (id),
--     num_val INTEGER
-- );

-- CREATE TABLE IF NOT EXISTS General_Data
-- (
--     id SERIAL PRIMARY KEY,
--     "date" DATE,
--     "hour" INTEGER,
--     line_name VARCHAR(255),
--     station_name VARCHAR(255),
--     num_val INTEGER,
--     input_doors_count INTEGER,
--     input_doors_bandwidth NUMERIC(10, 2),
--     input_doors_total_bandwidth NUMERIC(10, 2),
--     input_doors_note NUMERIC(10, 2),
--     input_turnstile_count INTEGER,
--     input_turnstile_bandwidth NUMERIC(10, 2),
--     input_turnstile_total_bandwidth NUMERIC(10, 2),
--     input_turnstile_note NUMERIC(10, 2),
--     input_stairs_width NUMERIC(10, 2),
--     input_stairs_bandwidth NUMERIC(10, 2),
--     input_stairs_total_bandwidth NUMERIC(10, 2),
--     input_escalator_count INTEGER,
--     input_escalator_bandwidth NUMERIC(10, 2),
--     input_escalator_total_bandwidth NUMERIC(10, 2),
--     output_doors_count INTEGER,
--     output_doors_bandwidth NUMERIC(10, 2),
--     output_doors_total_bandwidth NUMERIC(10, 2),
--     output_turnstile_count INTEGER,
--     output_turnstile_bandwidth NUMERIC(10, 2),
--     output_turnstile_total_bandwidth NUMERIC(10, 2),
--     output_stairs_width NUMERIC(10, 2),
--     output_stairs_bandwidth NUMERIC(10, 2),
--     output_stairs_total_bandwidth NUMERIC(10, 2),
--     output_escalator_count INTEGER,
--     output_escalator_bandwidth NUMERIC(10, 2),
--     output_escalator_total_bandwidth NUMERIC(10, 2),
--     stop_id INTEGER
-- )

CREATE TABLE IF NOT EXISTS TRIPS
(
    id SERIAL PRIMARY KEY,
    "date" DATE,
    "hour" INTEGER,
    line_name VARCHAR(255),
    station_name VARCHAR(255),
    num_val INTEGER,
    input_doors_count INTEGER,
    input_doors_bandwidth NUMERIC(10, 2),
    input_doors_total_bandwidth NUMERIC(10, 2),
    input_doors_note NUMERIC(10, 2),
    input_turnstile_count INTEGER,
    input_turnstile_bandwidth NUMERIC(10, 2),
    input_turnstile_total_bandwidth NUMERIC(10, 2),
    input_turnstile_note NUMERIC(10, 2),
    input_stairs_width NUMERIC(10, 2),
    input_stairs_bandwidth NUMERIC(10, 2),
    input_stairs_total_bandwidth NUMERIC(10, 2),
    input_escalator_count INTEGER,
    input_escalator_bandwidth NUMERIC(10, 2),
    input_escalator_total_bandwidth NUMERIC(10, 2),
    output_doors_count INTEGER,
    output_doors_bandwidth NUMERIC(10, 2),
    output_doors_total_bandwidth NUMERIC(10, 2),
    output_turnstile_count INTEGER,
    output_turnstile_bandwidth NUMERIC(10, 2),
    output_turnstile_total_bandwidth NUMERIC(10, 2),
    output_stairs_width NUMERIC(10, 2),
    output_stairs_bandwidth NUMERIC(10, 2),
    output_stairs_total_bandwidth NUMERIC(10, 2),
    output_escalator_count INTEGER,
    output_escalator_bandwidth NUMERIC(10, 2),
    output_escalator_total_bandwidth NUMERIC(10, 2),
    input_doors_total_bandwidth_coef NUMERIC(10, 2),
    clusters INTEGER
);
